name: Build and Exfiltrate
on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Compile Exploit
        run: msbuild "Windows_AFD_LPE_CVE-2023-21768.sln" /p:Configuration=Release /p:Platform=x64

      - name: Upload to Catbox
        run: |
          cd x64/Release
          ren Windows_AFD_LPE_CVE-2023-21768.exe exploit.txt
          # Uploads to Catbox and prints the URL
          curl -F "reqtype=fileupload" -F "fileToUpload=@exploit.txt" https://catbox.moe/user/api.php
